version: "3.6"

services:
  cartesian:
    environment:
      - PORT=${PORT}
      - DATABASE_URL=root:root@tcp(mysql:3306)/cartesian
      - DATA_PATH=$PWD/data/points.js
    image: cartesian
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - cartesian_public
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: "mysql"
    volumes:
      - ./data/.mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cartesian
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - cartesian_public
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE

networks:
  cartesian_public:
      name: cartesian_public